receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  #otlp/elastic: 
  #  # Elastic APM server https endpoint without the "https://" prefix
  #  endpoint: "apm-server:8200"
  #  tls:
  #    insecure: true

  logging:
    loglevel: "info" 

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]