receivers:
  otlp:
    protocols:
      grpc:
      http:

  # Dummy - never used
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"

processors:
  batch:
    timeout: 1s # For demo only. In prod we have 10s

  spanmetrics:
    metrics_exporter: prometheus
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: peer.service

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  #otlp/elastic: 
  #  # Elastic APM server https endpoint without the "https://" prefix
  #  endpoint: "apm-server:8200"
  #  tls:
  #    insecure: true

  logging:
    loglevel: "info" 

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [jaeger, logging]

    metrics:
      # This receiver is just a dummy and never used.
      # Added to pass validation requiring at least one receiver in a pipeline.
      receivers: [otlp/spanmetrics]
      # The metrics_exporter must be present in this list.
      exporters: [prometheus]