FROM otel/opentelemetry-collector-contrib
COPY ./config.yaml /etc/otelcol-contrib/config.yaml

EXPOSE 9200
EXPOSE 13133
EXPOSE 14250
EXPOSE 14268
EXPOSE 55678-55679
EXPOSE 4317
EXPOSE 8888
EXPOSE 9411