version: '3.4'

services:

  userdb:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssqlsvr
    hostname: mssqlsvr
    ports:
      - 1433:1433
    environment:
        SA_PASSWORD: "p@55w0rd"
        ACCEPT_EULA: "Y"
    networks:
      - weatherapi_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    container_name: authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile
    ports:
      - 8081:443
    networks:
      - weatherapi_net
    depends_on:
      - userdb

  forecastservice:
    image: ${DOCKER_REGISTRY-}forecastservice
    container_name: forecastservice
    build:
      context: .
      dockerfile: ForecastService/Dockerfile
    ports:
      - 8082:443
    networks:
      - weatherapi_net

  weatherapi:
    image: ${DOCKER_REGISTRY-}weatherapi
    build:
      context: .
      dockerfile: WeatherApi/Dockerfile
    ports:
      - 8080:443
    networks:
      - weatherapi_net
    depends_on:
      - forecastservice
      - authenticationservice

  collector:
    container_name: collector
    build: 
      context: C:/Users/Blake/source/repos/OtelTalk/src/Collector
    image: oteltalk-collector:latest
    ports:
      - 8888:8888
      - 4317:4317
      - 4318:4318
      - 8889:8889
    networks:
      - weatherapi_net

  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - weatherapi_net

  prometheus:
    container_name: prometheus
    build: 
      context: C:/Users/Blake/source/repos/OtelTalk/src/Prometheus
    image: oteltalk-prometheus:latest
    ports:
      - 9090:9090
    networks:
      - weatherapi_net

networks:
  weatherapi_net: